# Generated by Django 3.1.7 on 2021-03-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='roleslists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('edit hello', 'edit hello'), ('edit bolo', 'edit bolo')], max_length=100)),
            ],
        ),
    ]
