# Generated by Django 3.1.7 on 2021-03-21 14:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_roleslists'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='roleslists',
            name='title',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('edit hello', 'edit hello'), ('edit bolo', 'edit bolo')], max_length=20),
        ),
    ]
