# Generated by Django 3.1.7 on 2021-03-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_productslists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productslists',
            name='quantity',
        ),
    ]
