# Generated by Django 3.1.7 on 2021-03-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_remove_productslists_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslists',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
