# Generated by Django 3.1.7 on 2021-03-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0008_categorieslists'),
    ]

    operations = [
        migrations.CreateModel(
            name='saleslists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('sold_to', models.CharField(choices=[('Walk in Customer', 'Walk in Customer'), ('Vendor', 'vendor')], max_length=100)),
                ('items_sold', models.IntegerField()),
                ('total', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='stock_analysislists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='taxlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_percentage', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
