# Generated by Django 3.1.7 on 2021-03-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_saleslists_stock_analysislists_taxlists'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_analysislists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('total_sales', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
