# Generated by Django 3.1.7 on 2021-03-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_customer_analysislists'),
    ]

    operations = [
        migrations.CreateModel(
            name='tax_reportslists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('vendor', models.CharField(choices=[('Walk in Customer', 'Walk in Customer'), ('Vendor', 'vendor')], max_length=100)),
                ('product_tax', models.IntegerField()),
                ('grand_total', models.IntegerField()),
            ],
        ),
    ]
