# Generated by Django 3.1.7 on 2021-03-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0013_exp_categorieslists'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslists',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
