# Generated by Django 3.1.7 on 2021-03-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0014_saleslists_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productslists',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
