# Generated by Django 3.1.7 on 2021-03-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0017_customerlists_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslists',
            name='customer_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
