# Generated by Django 3.1.7 on 2021-03-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0018_saleslists_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslists',
            name='tax',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
