# Generated by Django 3.1.7 on 2021-03-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0019_saleslists_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslists',
            name='grand_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleslists',
            name='tax_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
