# Generated by Django 3.1.7 on 2021-03-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0022_auto_20210326_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleslists',
            name='Customer_box',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roleslists',
            name='Profile_box',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roleslists',
            name='Vendor_box',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roleslists',
            name='user_box',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
