# Generated by Django 3.1.7 on 2021-03-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_planlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerslists',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerslists',
            name='status',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
